---
name: 🐛 Bug Report
about: Report a bug or issue with the development environment
title: 'bug: [Brief description of the issue]'
labels: ['bug', 'needs-investigation']
assignees: ['bo7']
---

## 🐛 Bug Description
<!-- A clear and concise description of what the bug is -->

## 🔄 Steps to Reproduce
<!-- Steps to reproduce the behavior -->
1. 
2. 
3. 
4. 

## ✅ Expected Behavior
<!-- A clear and concise description of what you expected to happen -->

## ❌ Actual Behavior
<!-- A clear and concise description of what actually happened -->

## 📸 Screenshots
<!-- If applicable, add screenshots to help explain your problem -->

## 🌍 Environment
<!-- Please complete the following information -->
- OS: [e.g. macOS 13.0, Ubuntu 22.04, Windows 11]
- Docker Version: [e.g. 24.0.5]
- Git Version: [e.g. 2.42.0]
- Shell: [e.g. bash, zsh, fish]

## 📋 Setup Information
<!-- Please provide information about your setup -->
- [ ] Fresh clone of the repository
- [ ] Ran `./setup.sh` successfully
- [ ] Using fork-based workflow
- [ ] Working inside Docker container
- [ ] Using Claude Code integration

## 📝 Additional Context
<!-- Add any other context about the problem here -->

## 🧪 Debugging Information
<!-- If applicable, provide any error messages, logs, or debugging output -->

### Error Messages
```
[Paste error messages here]
```

### Docker Logs
```bash
# Run this command and paste output:
docker logs claude-dev-env
```

### Setup Script Output
```bash
# If setup failed, paste relevant output from ./setup.sh
```

## 💡 Possible Solution
<!-- If you have ideas on how to fix this, please share them -->

## 📚 Related Issues
<!-- Link any related issues or discussions -->
- Relates to #
- Duplicate of #
- Blocks #
